### ISSUE TITLE
external scripts not loading

### ISSUE THREAD

**Issue by meetar** [tangrams/differ-tests#4]
Scene files which specify a data source `scripts` parameter, eg:

``` yaml
sources:
    osm:
        type: TopoJSONTiles
        url:  http://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-HqUVidw
        scripts: ['external_script.js']
```

Load properly inside tangram-frame: http://tangrams.github.io/tangram-frame/?url=http://tangrams.github.io/differ-tests/unit-tests/sources/sources-scripts.yaml&lib=0.8#5/49.739/-56.206

But not when the same frame is loaded via the differ: http://tangrams.github.io/differ/?1=http%3A//tangrams.github.io/differ-tests/unit-tests/sources/sources-script.json&2=http%3A//tangrams.github.io/differ-tests/unit-tests/sources/sources-script.json&lib1=0.8&lib2=0.8

In the above example, the variable `testvar`, defined in https://github.com/tangrams/differ-tests/blob/gh-pages/unit-tests/sources/external_script.js, is not being retrieved by the test scenes, and the scene fails to load property or draw.
